### ISSUE TITLE
Fix expecting security data for unsecured operations

### ISSUE THREAD

**Issue by playpauseandstop** [playpauseandstop/rororo#114]
If `security` defined for all operations globally as,

```yaml
security:
  - jwt: []
```

and some operation declares empty `security` list like,

```yaml
paths:
  "/public":
    get:
      operationId: "retrieve_public_data"
      summary: "Retrieve public data"
      security: []
      ...
```

`rororo` still expected `retrieve_public_data` endpoint to receive data from `jwt` security scheme, which is wrong.

Need to fix and ensure that those operations do not require any secure data to work well.
