### ISSUE TITLE
Handle incorrect empty list as operation security

### ISSUE THREAD

**Issue by playpauseandstop** [playpauseandstop/rororo#117]
When OpenAPI operation schema do not define the security such as,

```yaml
get:
  operationId: "me"
  summary: "Retrieve user profile"
  tags: ["auth"]
  ...
```

`operation.security` still equals to empty list `[]`, not `None`, which result the fix from #115 result in incorrect handling of global defined `security`.

Need to find a way to fix this and ensure that global defined `security` work as expected for such cases.

Parent Issue: #114
