### ISSUE TITLE
Guess route prefix from OAS servers schema

### ISSUE THREAD

**Issue by playpauseandstop** [playpauseandstop/rororo#23]
Right now, when OAS `servers` schema looks like:

```yaml
servers:
  - url: "/api/"
    description: "Test environment"

  - url: "http://localhost:8080/api/"
    description: "Dev environment"

  - url: "https://staging.url/api/"
    description: "Staging environment"

  - url: "https://production.url/api/"
    description: "Production environment"
```

`setup_openapi` requires `route_prefix="/api"` to be passed or it will register OpenAPI operations to unexpected URLs. 

Need to find a way to not ask user to pass `route_prefix` by default and find out if it needed to be used from `servers` configuration.
