### ISSUE TITLE
Support optional security schemes

### ISSUE THREAD

**Issue by playpauseandstop** [playpauseandstop/rororo#29]
Need to ensure that optional security schemes is supported and result in passing security check by rororo.

Example of operation with optional security scheme,

```yaml
  security:
    - {}
    - apiKey: []
```

More details at: https://github.com/OAI/OpenAPI-Specification/issues/14
